import test from 'node:test';
import assert from 'node:assert/strict';
import { assertTargetGuard, buildManifest, toBit, toDate, transformRow, validateSource, reconciliationPlan, sequenceReconciliation, IDENTITY_TABLES } from '../scripts/migration/sqlite-to-mssql.js';

const base = { organizations: [{ id: 7, code: 'UCE', name: 'UCE', active: 1, created_at: '2025-01-01T00:00:00.000Z' }], roles: [], permissions: [], role_permissions: [], departments: [{ id: 2, organization_id: 7, name: 'TI', active: 1, created_at: '2025-01-01T00:00:00.000Z' }], categories: [], users: [], teams: [], team_members: [], tickets: [], canned_responses: [], ticket_comments: [], ticket_attachments: [], ticket_history: [], settings: [], org_settings: [], email_logs: [], notifications: [], kb_categories: [], kb_articles: [], kb_ticket_articles: [], kb_article_history: [], sequences: [], sessions: [] };
test('M4 conversiones estrictas de datetime y boolean', () => { assert.equal(toBit('true', 'x'), true); assert.throws(() => toBit('yes', 'x')); assert.equal(toDate('2025-01-01T00:00:00.123Z', 'x'), '2025-01-01T00:00:00.123Z'); assert.throws(() => toDate('2025-01-01 00:00:00', 'x')); });
test('M4 mapea org desde fila y no inventa una', () => { assert.equal(transformRow('departments', base.departments[0], base).organization_id, 7); assert.throws(() => transformRow('departments', { id: 3, name: 'x', active: 1, created_at: '2025-01-01T00:00:00Z' }, base)); });
test('M4 detecta huérfanos y duplicados', () => { const source = structuredClone(base); source.tickets = [{ id: 1, organization_id: 7, ticket_number: 'T-1', reporter_id: 99, created_at: '2025-01-01T00:00:00Z' }, { id: 2, organization_id: 7, ticket_number: 'T-1', reporter_id: 99, created_at: '2025-01-01T00:00:00Z' }]; assert.ok(validateSource(source).some((x) => /duplicado|inexistente/.test(x.error))); });
test('M4 guardas de destino rechazan instancias y bases prohibidas', () => { const valid = { DB_CLIENT: 'mssql', DB_SERVER: 'test-host', DB_INSTANCE: 'SIFHADEV', DB_DATABASE: 'M4_EMPTY', MIGRATION_TARGET_DATABASE: 'M4_EMPTY' }; assert.equal(assertTargetGuard(valid).database, 'M4_EMPTY'); assert.throws(() => assertTargetGuard({ ...valid, DB_SERVER: 'HPWJA' })); assert.throws(() => assertTargetGuard({ ...valid, DB_DATABASE: 'SIFHA_Tickets_DEV', MIGRATION_TARGET_DATABASE: 'SIFHA_Tickets_DEV' })); });
test('M4 manifest no expone secretos y declara reconciliación', () => { const manifest = buildManifest(base, { instance: 'SIFHADEV', database: 'M4_EMPTY' }); assert.equal(manifest.tables.sessions.skipped_count, 0); assert.ok(reconciliationPlan().verify.includes('ticket sequence')); });
test('M4 preserva identidad y reconcilia el máximo de cada secuencia', () => { assert.ok(IDENTITY_TABLES.has('tickets')); assert.equal(IDENTITY_TABLES.has('role_permissions'), false); assert.deepEqual(sequenceReconciliation([{ organization_id: 7, ticket_number: 'TCK-000002' }, { organization_id: 7, ticket_number: 'TCK-000010' }]), [{ name: 'ticket_number:7', value: 10 }]); });
